// Generated by tools/make_catalog.py — do not edit.
#pragma once
#include <pebble.h>

#define CAT_COUNT 2235
#define CAT_NAMES_OFF (2 + CAT_COUNT * 12)
#define CAT_CLASSES "OBAFGKMD?"

typedef struct __attribute__((packed)) {
  int16_t x, y, z;              // 0.01 ly, galactic
  uint16_t name_off;
  int8_t absmag4;               // absolute magnitude x4
  uint8_t spect;                // class nibble | subclass
  uint8_t con;                  // index into CAT_CONS, 0xFF none
  uint8_t reserved;
} StarRec;

#define CAT_N_CONS 88
static const char CAT_CONS[CAT_N_CONS][4] = {
  "And", "Ant", "Aps", "Aql", "Aqr", "Ara", "Ari", "Aur", "Boo", "CMa", "CMi", "CVn", "Cae", "Cam", "Cap", "Car", "Cas", "Cen", "Cep", "Cet", "Cha", "Cir", "Cnc", "Col", "Com", "CrA", "CrB", "Crt", "Cru", "Crv", "Cyg", "Del", "Dor", "Dra", "Equ", "Eri", "For", "Gem", "Gru", "Her", "Hor", "Hya", "Hyi", "Ind", "LMi", "Lac", "Leo", "Lep", "Lib", "Lup", "Lyn", "Lyr", "Men", "Mic", "Mon", "Mus", "Nor", "Oct", "Oph", "Ori", "Pav", "Peg", "Per", "Phe", "Pic", "PsA", "Psc", "Pup", "Pyx", "Ret", "Scl", "Sco", "Sct", "Ser", "Sex", "Sge", "Sgr", "Tau", "Tel", "TrA", "Tri", "Tuc", "UMa", "UMi", "Vel", "Vir", "Vol", "Vul"
};
